### ISSUE TITLE
Exception when trying to access "Saves"

### ISSUE THREAD

**Issue by shenef** [GB127/SRC-statistics#81] opened 2021-07-29 21:47 UTC
Replicated on accounts: "shenef", "1"

```Traceback (most recent call last):
  File "main.py", line 8, in <module>
    user()
  File "F:\_PROGRAMS\SRC-Statistics\user.py", line 41, in __call__
    self.__dict__[command]()
  File "F:\_PROGRAMS\SRC-Statistics\generic.py", line 78, in __call__
    self.data.sort()
  File "F:\_PROGRAMS\SRC-Statistics\generic.py", line 159, in __lt__
    raise BaseException(f'\n{self}\n{other}\n{list(self.__dict__.keys())}')
BaseException:
 GBA   | Boktai: The Sun is in Your Han | Any%                 | 27  |   0:09:05 |   0:00:20 |  -0:08:45 |   96.33 % |   0:00:11
 GBA   | Boktai: The Sun is in Your Han | Any%                 | 27  |   0:09:05 |   0:00:20 |  -0:08:45 |   96.33 % |   0:00:19
['system', 'game', 'category', 'runs', 'count', 'first', 'time', 'delta', 'perc1st', 'WR']```

**Comment by GB127** [comment] 2021-08-01 02:07
@shenef  Here is a tempo fix I made for this. Since currently there are no way to get an error except by having some unlikely scenario, I added a small line.

I'm planning to do some rewrite concerning levels runs and the rewrite will have this issue fixed more properly.

In the mean time, thank to this fix, you can access to the table. however, those two runs (and maybe others?) may not be sorted correctly (IE not in alphabetic order).

**Comment by GB127** [comment] 2021-08-01 02:09
By the way, it's a duplicate of #80 .

**Closed by GB127** 2021-08-01 02:09 UTC
